apiVersion: v1
baseDomain: aoicloud.xyz
metadata:
  name: ocp4
networking:
  machineCIDR: 10.0.0.0/24
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIPs:
      - 10.0.0.10
    ingressVIPs:
      - 10.0.0.12
    provisioningNetworkCIDR: 172.22.0.0/24
    bootstrapProvisioningIP: 172.22.0.6
    clusterProvisioningIP: 172.22.0.10
    provisioningDHCPRange: 172.22.0.11,172.22.0.30
    bootstrapExternalStaticIP: 10.0.0.6
    bootstrapExternalStaticGateway: 10.0.0.2
    bootstrapExternalStaticDNS: 10.0.0.2
    hosts:
      - name: cp01
        role: master
        bmc:
          address: ipmi://10.10.0.1:60079
          username: secret
          password: secret
        bootMACAddress: 52:54:00:3a:53:f1
        rootDeviceHints:
          deviceName: "/dev/vda"
        networkConfig:
          interfaces:
          - name: bond0
            type: bond
            state: up
            link-aggregation:
              mode: 'active-backup'
              options:
                miimon: '100'
              port:
              - ens4
              - ens5
            mtu: 1500
          - name: vlan100
            type: vlan
            state: up
            vlan:
              id: 100
              base-iface: bond0
            ipv4:
              address:
              - ip: 10.0.0.60
                prefix-length: 24
              enabled: true
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.0.0.2
                next-hop-interface: vlan100
          dns-resolver:
            config:
              server:
                - 10.0.0.2
      - name: cp02
        role: master
        bmc:
          address: ipmi://10.10.0.1:60080
          username: secret
          password: secret
        bootMACAddress: 52:54:00:05:50:30
        rootDeviceHints:
          deviceName: "/dev/vda"
        networkConfig:
          interfaces:
          - name: bond0
            type: bond
            state: up
            link-aggregation:
              mode: 'active-backup'
              options:
                miimon: '100'
              port:
              - ens4
              - ens5
            mtu: 1500
          - name: vlan100
            type: vlan
            state: up
            vlan:
              id: 100
              base-iface: bond0
            ipv4:
              address:
              - ip: 10.0.0.61
                prefix-length: 24
              enabled: true
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.0.0.2
                next-hop-interface: vlan100
          dns-resolver:
            config:
              server:
                - 10.0.0.2
      - name: cp03
        role: master
        bmc:
          address: ipmi://10.10.0.1:60081
          username: secret
          password: secret
        bootMACAddress: 52:54:00:e0:a3:ec
        rootDeviceHints:
          deviceName: "/dev/vda"
        networkConfig:
          interfaces:
          - name: bond0
            type: bond
            state: up
            link-aggregation:
              mode: 'active-backup'
              options:
                miimon: '100'
              port:
              - ens4
              - ens5
            mtu: 1500
          - name: vlan100
            type: vlan
            state: up
            vlan:
              id: 100
              base-iface: bond0
            ipv4:
              address:
              - ip: 10.0.0.62
                prefix-length: 24
              enabled: true
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.0.0.2
                next-hop-interface: vlan100
          dns-resolver:
            config:
              server:
                - 10.0.0.2
      - name: comp01
        role: worker
        bmc:
          address: ipmi://10.10.0.1:60078
          username: secret
          password: secret
        bootMACAddress: 52:54:00:0a:6e:01
        rootDeviceHints:
          deviceName: "/dev/vda"
        hardwareProfile: unknown
        networkConfig:
          interfaces:
          - name: bond0
            type: bond
            state: up
            link-aggregation:
              mode: 'active-backup'
              options:
                miimon: '100'
              port:
              - ens4
              - ens5
            mtu: 1500
          - name: vlan100
            type: vlan
            state: up
            vlan:
              id: 100
              base-iface: bond0
            ipv4:
              address:
              - ip: 10.0.0.63
                prefix-length: 24
              enabled: true
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.0.0.2
                next-hop-interface: vlan100
          dns-resolver:
            config:
              server:
                - 10.0.0.2
      - name: comp02
        role: worker
        bmc:
          address: ipmi://10.10.0.1:60077
          username: secret
          password: secret
        bootMACAddress: 52:54:00:9a:48:34
        rootDeviceHints:
          deviceName: "/dev/vda"
        hardwareProfile: unknown
        networkConfig:
          interfaces:
          - name: bond0
            type: bond
            state: up
            link-aggregation:
              mode: 'active-backup'
              options:
                miimon: '100'
              port:
              - ens4
              - ens5
            mtu: 1500
          - name: vlan100
            type: vlan
            state: up
            vlan:
              id: 100
              base-iface: bond0
            ipv4:
              address:
              - ip: 10.0.0.64
                prefix-length: 24
              enabled: true
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.0.0.2
                next-hop-interface: vlan100
          dns-resolver:
            config:
              server:
                - 10.0.0.2
pullSecret: '$(< ~/pull-secret.txt)'
sshKey: '$(< ~/.ssh/id_rsa.pub)'
EOF
[kni@provisioner ~]$
